version: 0.2

phases:
  install:
    commands:
      - cd weather-prophet-app
      - rm -rf node_modules/
      - sudo npm install -g @angular/cli
      - sudo npm install
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3 sync ./dist s3://weather-prophet
